version: '3'

services:
  user:
    build: ./services/user
    restart: always
    hostname: user
    env_file:
      - .env.test
    networks:
      - backend
    links:
      - db
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
  db:
    image: 'mongo:3.7'
    restart: always
    hostname: db
    environment:
      MONGO_DSN: ${MONGO_DSN}
    volumes:
      - "./db/init/:/docker-entrypoint-initdb.d/"
    networks:
      - backend
    ports:
      - 27017:27017

networks:
  backend:
    driver: bridge